### ISSUE TITLE
Cannot simulate delegated events (e.g. click)

### ISSUE THREAD

**Issue by jlchereau** [jquery/jquery-simulate#33]

**Comment by scottgonzalez** [comment]
There's no such thing as a delegated event. The simulated events bubble, and that's what event delegation is.

**Comment by jlchereau** [comment]
Thank you. In the meantime I have found the ```bubbles``` option in the code.

**Comment by jlchereau** [comment]
```js
el.simulate( "drag", {
    bubbles: true,    
    moves: 5,
    dx: 10,
    dy: 20
});
```
does not seem to work:
options is discarded. coord(clientX, clientY) is used instead.

**Comment by scottgonzalez** [comment]
Please provide a reduced test case. It's not at all clear what you're trying to do.

**Comment by j-ulrich** [comment]
@jlchereau: Could it be that you are using jquery-simulate-ext? Then this issue should be created [there](https://github.com/j-ulrich/jquery-simulate-ext).

**Comment by jlchereau** [comment]
First, thank you for being so responsive.

I have been able to work around the issue at https://github.com/Memba/Kidoju-Widgets/blob/master/test/browsers/kidoju.widgets.stage.test.js#L529

I am testing the stage component represented below:
![image](https://cloud.githubusercontent.com/assets/2556751/6606491/bf7d9edc-c82f-11e4-8f14-2d2729d3ce47.png)

A drag operation:

- starts with a mousedown event on a handle,
- progresses with mousemove events on a stage element ($(item)),
- ends with a mouseup event on the same stage element.

Using jQuery delegated events, the event handlers are wired on the stage. 

Accordingly jQuery.simulate is used as follows:

```js
var center = findCenter(handle), moves = 10, dx = 100, dy = 50,
    x = center.x, y = center.y;
//initiate drag with mousedown event
handle.simulate('mousedown', { bubbles: true, clientX: x, clientY: y }); //initiate drag on move handle
//move item
for (var i = 0; i < moves; i++) {
    x += dx / moves;
    y += dy / moves;
    $(item).simulate('mousemove', { bubbles: true, clientX: x, clientY: y });
}
//end drag with mouseup event
$(item).simulate('mouseup', { bubbles: true, clientX: x, clientY: y });
```
I have not been able to use $.simulate('drag', options) to achieve the same. Hope this clarifies the need.

**Comment by scottgonzalez** [comment]
This is actually intentional. Since mouse events don't have pointer capturing, there's no guarantee that the `mousemove` and `mouseup` events will occur on the intended element. The user can move their mouse too fast, so the proper way to implement drag functionality is to bind to events on the document for those events.

**Comment by jlchereau** [comment]
Many thanks.
