### ISSUE TITLE
Error with HTTPs

### ISSUE THREAD

**Issue by noelboss** [jquery/jquery-simulate#35]
Blocked a frame with origin "..." from accessing a frame with origin "...". Protocols, domains, and ports must match.

Uncaught SecurityError: Blocked a frame with origin "..." from accessing a frame with origin "...". Protocols, domains, and ports must match.

caused by line 25;
if (window.frames[i].document === doc) {

in https://cdn.rawgit.com/j-ulrich/jquery-simulate-ext/1.3.0/libs/jquery.simulate.js

Chrome and Firefox stopp execution, Safari continues...

**Comment by j-ulrich** [comment]
That line comes from the modifications I made to jquery simulate in the [jquery-simulate-ext repo](https://github.com/j-ulrich/jquery-simulate-ext). So that issues should probably rather be posted there.
