### ISSUE TITLE
drag and drop refer to document while they should refer to element

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [jquery/jquery-simulate#38]
if you implement a drag by binding all events 'mousedown','mousemove','mouseup' to the element, simulate will not be able to move the element as it dispatches even on doc instead of element. 

This can be reproduced based on the plunker : http://plnkr.co/edit/fNL8esuTYapkj48p6XkO?p=preview

currently includes the fix - so you need to change simulate.js to reproduce the bug

**Comment by scottgonzalez** [comment]
That's correct. This is intentional because if you bind to the element, then your drag functionality is broken. The user can very easily move the mouse fast enough to come off of the element.

**Comment by guy-mograbi-at-gigaspaces** [comment]
I agree, but some 3rd-parties have other implementations rather than listening on the entire document, which might be fine for their scenarios. perhaps we can allow to configure what is considered the document?

**Comment by scottgonzalez** [comment]
I'd prefer not to complicate the API as I suspect this whole module will be deprecated soon in favor of using Web Driver.
