### ISSUE TITLE
Why not active development?

### ISSUE THREAD

**Issue by adjohnson916** [jquery/jquery-simulate#43]
Is there a reason this isn't under active development that someone (e.g. @jzaefferer or @scottgonzalez) can explain more fully than the bit in the README?

Was it determined to be too difficult or impossible to simulate some of these events in even just the popular browsers? Or maybe it was just because Selenium was and is still popular?

A downside with Selenium and its WebDriver API is that it can't attach to existing browsers, but instead controls the whole browser lifecycle, so I feel there's still value in a library like this for the use case of injecting scripts into open pages.

**Comment by dmethvin** [comment]
Once the project does what its creators needed it to do, there isn't a lot of reason to continue adding features. Do you have some things you think it should do?

**Comment by adjohnson916** [comment]
@dmethvin I wanted to rule out any technical limitations that led to its abandonment, so I know whether or not to rely on it in a new project.

**Comment by scottgonzalez** [comment]
It's pretty stable. We've been using it in jQuery UI for several years (it's where the project originated). We will eventually move to Web Driver tests, but using jquery-simulate is a much easier step toward better tests. We haven't need any additional features, so it hasn't been actively maintained.
