### ISSUE TITLE
Simulating selecting an option in a <select> tag

### ISSUE THREAD

**Issue by rkpatel33** [jquery/jquery-simulate#46]
How would I simulate clicking on an option in a select tag? I am using this code but it's not updating the actual page. It could be special validation in the web page, but thought I would ask.

$('#state option').filter('[value=3]').simulate('click');

The page in question is here, the `State` dropdown:

https://www.upstart.com/funding_form

Thx.

**Comment by scottgonzalez** [comment]
The `click` event is not what causes an option to be selected. To mimic that, just change the value and trigger a `change` event.

**Comment by rkpatel33** [comment]
It seems the following snippet still does not trigger the events needed on
this page to set the validation classes that get changed when set for real.


$("#state").val(10);
$(“#state").trigger('change');

If you have any other ideas, they would be appreciated. Looks like it is
some odd custom code.



_________________________
Rishi Patel | mail@rishinyc.com
