### ISSUE TITLE
Dropdown expansion does not work on Chrome Version 53.0.2785.101 (64-bit)

### ISSUE THREAD

**Issue by juacompe** [jquery/jquery-simulate#47]
See this fiddle <http://jsfiddle.net/e59rqyn0/>.

It was working on Chrome Version 51.0.2704.106 (64-bit).

**Comment by scottgonzalez** [comment]
I wouldn't have expected this to work. This is for simulating events for the purpose of JavaScript testing. It is not for simulating actual user actions; for that you need to use Web Driver.
